version: '3.3'

services:

  chatbot:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: chatbot
    privileged: true
    environment:
      - DISPLAY=${DISPLAY}
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    volumes:
      - .:/home/developer
      - /tmp/.X11-unix:/tmp/.X11-unix
